import React from "react";

export const routes = [
  {
    to: null,
    title: "Creación de componentes",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem1",
    title: "Componente usando clases",
    description: "Muestra como crear un componente usando clases. Obsoleto.",
    component: React.lazy(() => import("../pages/Ejem_01")),
  },
  {
    to: "Ejem2",
    title: "Componente dentro de otros componentes",
    description: "Uso de componentes anidados",
    component: React.lazy(() => import("../pages/Ejem_02")),
  },
  {
    to: "Ejem3",
    title: "Componente dentro de otros componentes",
    description: "Uso de if",
    component: React.lazy(() => import("../pages/Ejem_03")),
  },
  {
    to: "Ejem4",
    title: "Props",
    description: "Paso de props a componentes",
    component: React.lazy(() => import("../pages/Ejem_04")),
  },
  {
    to: "Ejem5",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_05")),
  },
  {
    to: "Ejem6",
    title: "Comunicacion hijo padre",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_06")),
  },
  {
    to: "Ejem7",
    title: "hook useState",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_07")),
  },
  {
    to: "Ejem8",
    title: "Pasar los hijos de un componente",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_08")),
  },
  {
    to: "Ejem9",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_09")),
  },
  {
    to: "Ejem10",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_10")),
  },
  {
    to: "Ejem11",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_11")),
  },
  {
    to: "Ejem12",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_12")),
  },
  {
    to: "Ejem13",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_13")),
  },
  {
    to: "Ejem14",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_14")),
  },
  {
    to: "Ejem15",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_15")),
  },
  {
    to: "Ejem16",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_16")),
  },
  {
    to: "Ejem17",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_17")),
  },
  {
    to: "Ejem18",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_18")),
  },
  {
    to: "Ejem19",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_19")),
  },
  {
    to: "Ejem20",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_20")),
  },
  {
    to: "Ejem21",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_21")),
  },
  {
    to: "Ejercicio01",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_01")),
  },
  {
    to: "Ejercicio02",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_02")),
  },
  {
    to: "Ejercicio03",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_03")),
  },
  {
    to: "Ejercicio04",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_04")),
  },
  {
    to: "Ejercicio05",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_05")),
  },
  {
    to: "Ejercicio06",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_06")),
  },
  {
    to: "Ejercicio07",
    title: "Bitcoin",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_07")),
  },
  
];
