# Imagen base con python
FROM python:3.11-slim

# Crea el directorio de trabajo
WORKDIR /app

# Copiar dependencias primero (para aprovechar la chaché de docker)
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir flask

# Copiar el código de la aplicación
COPY . .

# Exponer el puerto en el que correrá la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
